import { Meal, Goal, ActivityLevel, DietaryPreference, Cuisine } from './types';

const BASE_MEALS: Meal[] = [
    { id: 1, name: "Oatmeal with Berries", category: "Breakfast", calories: 350, macros: { protein: 10, carbs: 60, fat: 8 }, preferences: ["Vegetarian", "Dairy-Free", "Nut-Free"], cuisines: ["American"], goals: [Goal.WEIGHT_LOSS, Goal.MAINTAIN_WEIGHT, Goal.BOOST_ENERGY], description: "A warm and hearty start to your day.", why: "High in soluble fiber for sustained energy release and heart health." },
    { id: 2, name: "Greek Yogurt Parfait", category: "Breakfast", calories: 400, macros: { protein: 30, carbs: 40, fat: 15 }, preferences: ["Vegetarian", "Gluten-Free"], cuisines: ["American"], goals: [Goal.MUSCLE_GAIN, Goal.MAINTAIN_WEIGHT], description: "Layers of yogurt, granola, and fruit.", why: "Excellent source of protein for muscle repair and satiety." },
    { id: 3, name: "Scrambled Tofu", category: "Breakfast", calories: 300, macros: { protein: 20, carbs: 10, fat: 20 }, preferences: ["Vegetarian", "Gluten-Free", "Dairy-Free"], cuisines: ["American"], goals: [Goal.MUSCLE_GAIN, Goal.WEIGHT_LOSS], description: "A savory, plant-based alternative to eggs.", why: "A complete plant-based protein, rich in iron and calcium." },
    { id: 4, name: "Grilled Chicken Salad", category: "Lunch", calories: 450, macros: { protein: 40, carbs: 20, fat: 25 }, preferences: ["Non-Vegetarian", "Gluten-Free", "Dairy-Free", "Nut-Free"], cuisines: ["American"], goals: [Goal.WEIGHT_LOSS, Goal.MUSCLE_GAIN], description: "Lean protein with fresh, crisp vegetables.", why: "High in protein to keep you full and support muscle, low in carbs." },
    { id: 5, name: "Quinoa Bowl with Black Beans", category: "Lunch", calories: 500, macros: { protein: 20, carbs: 80, fat: 12 }, preferences: ["Vegetarian", "Gluten-Free", "Dairy-Free"], cuisines: ["Mexican"], goals: [Goal.BOOST_ENERGY, Goal.MAINTAIN_WEIGHT], description: "A vibrant and filling plant-powered bowl.", why: "Complex carbohydrates and complete protein from quinoa provide lasting energy." },
    { id: 6, name: "Lentil Soup", category: "Lunch", calories: 350, macros: { protein: 18, carbs: 60, fat: 5 }, preferences: ["Vegetarian", "Gluten-Free", "Dairy-Free", "Nut-Free"], cuisines: ["Indian"], goals: [Goal.WEIGHT_LOSS, Goal.BOOST_ENERGY], description: "A warm, nourishing, and fiber-rich soup.", why: "Extremely high in fiber, promoting digestive health and long-lasting fullness." },
    { id: 7, name: "Salmon with Roasted Asparagus", category: "Dinner", calories: 550, macros: { protein: 45, carbs: 15, fat: 35 }, preferences: ["Non-Vegetarian", "Pescatarian", "Gluten-Free", "Dairy-Free", "Nut-Free"], cuisines: ["American"], goals: [Goal.MUSCLE_GAIN, Goal.WEIGHT_LOSS, Goal.BETTER_SKIN], description: "Rich in omega-3s and perfectly cooked.", why: "Omega-3 fatty acids are crucial for brain health, reducing inflammation, and promoting healthy skin." },
    { id: 8, name: "Chicken and Vegetable Stir-fry", category: "Dinner", calories: 500, macros: { protein: 35, carbs: 50, fat: 18 }, preferences: ["Non-Vegetarian", "Dairy-Free"], cuisines: ["Asian"], goals: [Goal.MAINTAIN_WEIGHT, Goal.MUSCLE_GAIN], description: "A quick, colorful, and balanced meal.", why: "A great balance of macronutrients and packed with vitamins from various vegetables." },
    { id: 9, name: "Whole Wheat Pasta with Pesto", category: "Dinner", calories: 600, macros: { protein: 20, carbs: 90, fat: 18 }, preferences: ["Vegetarian"], cuisines: ["Italian"], goals: [Goal.BOOST_ENERGY, Goal.MAINTAIN_WEIGHT], description: "Classic Italian comfort food, made healthier.", why: "Whole wheat provides complex carbs for slow energy release through the night." },
    { id: 10, name: "Apple Slices with Peanut Butter", category: "Snack", calories: 250, macros: { protein: 8, carbs: 30, fat: 12 }, preferences: ["Vegetarian", "Gluten-Free", "Dairy-Free"], cuisines: ["American"], goals: [Goal.BOOST_ENERGY, Goal.MAINTAIN_WEIGHT], description: "A crunchy, sweet, and satisfying snack.", why: "Combines fiber from the apple and healthy fats/protein from peanut butter for satiety." },
    { id: 11, name: "Handful of Almonds", category: "Snack", calories: 180, macros: { protein: 6, carbs: 6, fat: 15 }, preferences: ["Vegetarian", "Gluten-Free", "Dairy-Free"], cuisines: ["American"], goals: [Goal.WEIGHT_LOSS, Goal.MUSCLE_GAIN, Goal.IMPROVE_SLEEP], description: "A simple, nutrient-dense snack.", why: "Rich in healthy monounsaturated fats, fiber, protein and magnesium, which aids sleep." },
    { id: 12, name: "Protein Shake", category: "Snack", calories: 200, macros: { protein: 25, carbs: 10, fat: 5 }, preferences: ["Vegetarian", "Gluten-Free"], cuisines: ["American"], goals: [Goal.MUSCLE_GAIN], description: "A quick and easy way to boost protein intake.", why: "Fast-absorbing protein ideal for post-workout muscle recovery." },
    { id: 13, name: "Chana Masala", category: "Dinner", calories: 450, macros: { protein: 15, carbs: 70, fat: 12 }, preferences: ["Vegetarian", "Gluten-Free", "Dairy-Free", "Nut-Free"], cuisines: ["Indian"], goals: [Goal.BOOST_ENERGY, Goal.MAINTAIN_WEIGHT], description: "A flavorful and spicy chickpea curry.", why: "Chickpeas are an excellent source of plant-based protein and fiber." },
    { id: 14, name: "Burrito Bowl", category: "Lunch", calories: 550, macros: { protein: 30, carbs: 65, fat: 20 }, preferences: ["Non-Vegetarian", "Gluten-Free"], cuisines: ["Mexican"], goals: [Goal.MUSCLE_GAIN, Goal.MAINTAIN_WEIGHT], description: "All the goodness of a burrito, without the wrap.", why: "Customizable and balanced, providing a mix of protein, carbs, and healthy fats." },
    { id: 15, name: "Margherita Pizza on Whole Wheat Crust", category: "Dinner", calories: 650, macros: { protein: 25, carbs: 80, fat: 25 }, preferences: ["Vegetarian"], cuisines: ["Italian"], goals: [Goal.MAINTAIN_WEIGHT], description: "A classic pizza with a healthy twist.", why: "Using a whole wheat crust adds fiber and nutrients compared to white flour." },
    { id: 16, name: "Avocado Toast with Egg", category: "Breakfast", calories: 380, macros: { protein: 20, carbs: 30, fat: 20 }, preferences: ["Vegetarian", "Dairy-Free"], cuisines: ["American"], goals: [Goal.MUSCLE_GAIN, Goal.MAINTAIN_WEIGHT, Goal.BETTER_SKIN], description: "A trendy and nutritious breakfast choice.", why: "A balanced meal with healthy fats from avocado for skin health, protein from egg, and complex carbs from toast." },
    { id: 17, name: "Edamame", category: "Snack", calories: 150, macros: { protein: 12, carbs: 10, fat: 5 }, preferences: ["Vegetarian", "Gluten-Free", "Dairy-Free", "Nut-Free"], cuisines: ["Asian", "Japanese"], goals: [Goal.WEIGHT_LOSS, Goal.MUSCLE_GAIN], description: "Steamed young soybeans in the pod.", why: "A low-calorie snack that is surprisingly high in protein and fiber." },
    { id: 18, name: "Pad Thai with Tofu", category: "Dinner", calories: 600, macros: { protein: 25, carbs: 90, fat: 15 }, preferences: ["Vegetarian", "Dairy-Free"], cuisines: ["Asian"], goals: [Goal.BOOST_ENERGY], description: "A classic Thai noodle dish, full of flavor.", why: "A high-carbohydrate meal perfect for replenishing glycogen stores." },
    { id: 19, name: "Veggie Burger on Whole Wheat Bun", category: "Lunch", calories: 450, macros: { protein: 20, carbs: 60, fat: 15 }, preferences: ["Vegetarian"], cuisines: ["American"], goals: [Goal.MAINTAIN_WEIGHT], description: "A satisfying and plant-based alternative to a classic.", why: "Can be high in fiber and nutrients depending on the patty ingredients." },
    { id: 20, name: "Cottage Cheese with Fruit", category: "Snack", calories: 180, macros: { protein: 25, carbs: 15, fat: 2 }, preferences: ["Vegetarian", "Gluten-Free", "Nut-Free"], cuisines: ["American"], goals: [Goal.MUSCLE_GAIN, Goal.WEIGHT_LOSS], description: "A creamy, high-protein snack.", why: "High in casein protein, which digests slowly, providing a steady release of amino acids." }
];

const NEW_MEALS: Meal[] = [
    { id: 21, name: "Keto Avocado Egg Salad", category: "Lunch", calories: 450, macros: { protein: 20, carbs: 10, fat: 40 }, preferences: ["Keto", "Gluten-Free", "Vegetarian"], cuisines: ["American"], goals: [Goal.WEIGHT_LOSS], description: "Creamy egg salad with healthy fats.", why: "High fat and low carb content promotes ketosis for effective weight loss." },
    { id: 22, name: "Mediterranean Grilled Halloumi Salad", category: "Dinner", calories: 500, macros: { protein: 25, carbs: 30, fat: 30 }, preferences: ["Vegetarian", "Gluten-Free"], cuisines: ["Mediterranean"], goals: [Goal.MAINTAIN_WEIGHT, Goal.MUSCLE_GAIN], description: "Salty, savory grilled cheese with fresh vegetables.", why: "A balanced meal with good protein and fats, common in heart-healthy Mediterranean diets." },
    { id: 23, name: "Paleo Steak with Sweet Potato", category: "Dinner", calories: 600, macros: { protein: 50, carbs: 40, fat: 25 }, preferences: ["Non-Vegetarian", "Paleo", "Gluten-Free", "Dairy-Free"], cuisines: ["American"], goals: [Goal.MUSCLE_GAIN], description: "A hearty and satisfying whole-foods meal.", why: "High in protein for muscle building and includes complex carbs for energy, adhering to Paleo principles." },
    { id: 24, name: "Chamomile Banana Smoothie", category: "Snack", calories: 200, macros: { protein: 5, carbs: 40, fat: 3 }, preferences: ["Vegetarian", "Gluten-Free", "Dairy-Free"], cuisines: ["American"], goals: [Goal.IMPROVE_SLEEP], description: "A soothing smoothie to help you unwind.", why: "Chamomile is a natural relaxant, and bananas contain magnesium and potassium which can help with sleep." },
    { id: 25, name: "Salmon and Avocado Sushi Roll", category: "Lunch", calories: 480, macros: { protein: 35, carbs: 40, fat: 20 }, preferences: ["Non-Vegetarian", "Pescatarian", "Dairy-Free"], cuisines: ["Japanese", "Asian"], goals: [Goal.BETTER_SKIN, Goal.WEIGHT_LOSS], description: "Rich in omega-3s for a healthy glow.", why: "The omega-3s in salmon and healthy fats in avocado are known to support skin hydration and elasticity." },
    { id: 26, name: "Bouillabaisse (French Fish Stew)", category: "Dinner", calories: 550, macros: { protein: 40, carbs: 35, fat: 25 }, preferences: ["Non-Vegetarian", "Pescatarian", "Dairy-Free"], cuisines: ["French"], goals: [Goal.MAINTAIN_WEIGHT], description: "A classic Provençal fish stew.", why: "A flavorful way to get lean protein and a variety of nutrients from different types of seafood." },
    { id: 27, name: "Jerk Chicken with Rice and Peas", category: "Dinner", calories: 620, macros: { protein: 45, carbs: 70, fat: 18 }, preferences: ["Non-Vegetarian", "Dairy-Free", "Gluten-Free"], cuisines: ["Caribbean"], goals: [Goal.MUSCLE_GAIN, Goal.BOOST_ENERGY], description: "Spicy, flavorful chicken with traditional sides.", why: "A balanced, high-protein meal with complex carbs for sustained energy." }
];

export const MEALS: Meal[] = [...BASE_MEALS, ...NEW_MEALS];

export const GOALS = [
    { id: Goal.WEIGHT_LOSS, title: 'Weight Loss', description: 'Create a calorie deficit to shed pounds healthily.' },
    { id: Goal.MUSCLE_GAIN, title: 'Muscle Gain', description: 'Fuel your body with sufficient protein and calories.' },
    { id: Goal.MAINTAIN_WEIGHT, title: 'Maintain Weight', description: 'Keep your current weight with a balanced diet.' },
    { id: Goal.BOOST_ENERGY, title: 'Boost Energy', description: 'Eat for sustained energy throughout the day.' },
    { id: Goal.IMPROVE_SLEEP, title: 'Improve Sleep', description: 'Eat foods that promote restful sleep.' },
    { id: Goal.BETTER_SKIN, title: 'Better Skin Health', description: 'Nutrients for a clear and glowing complexion.' },
];

export const ACTIVITY_LEVELS = [
    { id: ActivityLevel.SEDENTARY, name: 'Sedentary', multiplier: 1.2, description: 'Little or no exercise' },
    { id: ActivityLevel.LIGHTLY_ACTIVE, name: 'Lightly Active', multiplier: 1.375, description: 'Light exercise/sports 1-3 days/week' },
    { id: ActivityLevel.MODERATELY_ACTIVE, name: 'Moderately Active', multiplier: 1.55, description: 'Moderate exercise/sports 3-5 days/week' },
    { id: ActivityLevel.VERY_ACTIVE, name: 'Very Active', multiplier: 1.725, description: 'Hard exercise/sports 6-7 days a week' },
    { id: ActivityLevel.EXTRA_ACTIVE, name: 'Extra Active', multiplier: 1.9, description: 'Very hard exercise/sports & physical job' },
];

export const DIETARY_PREFERENCES: DietaryPreference[] = ['Vegetarian', 'Non-Vegetarian', 'Gluten-Free', 'Dairy-Free', 'Nut-Free', 'Keto', 'Paleo', 'Pescatarian', 'Low-FODMAP'];

export const CUISINES: Cuisine[] = ['Italian', 'Indian', 'Mexican', 'Asian', 'American', 'Mediterranean', 'Japanese', 'French', 'Caribbean'];